config/routes.rb
Rails.application.routes.draw do
  root 'simple_pages#index'
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBikes</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="#">SuperBikes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav><!-- end navbar -->

    <div id="wrapper">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">SuperBikes</p>
      </div>
    </footer><!-- end footer -->
  </body>
</html>

app/views/simple_pages/about.html.erb
<section id="about" class="content">
  <h1 class="text-center">SuperBikes</h1>
  <p>
    Lorem ipsum dolor amet biodiesel DIY blue bottle gastropub shaman pickled XOXO gluten-free keytar. Brunch plaid iceland shoreditch pickled four dollar toast enamel pin seitan cold-pressed. Letterpress mlkshk poutine readymade poke actually whatever vinyl. Palo santo meh pour-over, copper mug green juice gastropub vinyl ethical locavore tumblr banjo try-hard.

    Crucifix 90's fashion axe, williamsburg roof party cronut authentic. Intelligentsia pabst YOLO dreamcatcher gentrify polaroid, try-hard drinking vinegar shaman echo park before they sold out. Locavore enamel pin tilde, tbh raclette wayfarers cornhole chartreuse slow-carb man bun post-ironic actually forage brunch shoreditch. Chia sriracha normcore, sartorial distillery tilde shoreditch iceland shabby chic. Fashion axe lyft mlkshk, bespoke neutra hashtag cornhole plaid.

    Helvetica craft beer brunch street art slow-carb palo santo godard forage umami. Adaptogen squid vinyl hell of pok pok. Four loko af raclette copper mug cred hella. Af shoreditch authentic twee craft beer four loko tousled pop-up mixtape asymmetrical etsy chillwave chambray. Viral hella next level bushwick affogato bespoke fanny pack vinyl pour-over. Banjo slow-carb thundercats, vape retro shabby chic seitan pabst cronut poke gentrify wolf post-ironic. Locavore waistcoat freegan letterpress messenger bag mixtape cray shoreditch forage ugh actually beard vinyl.
  </p>
</section>

app/views/simple_pages/contact.html.erb
<section id="contact">
  <div>
    <div class="row">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-12">
            <div>
              <h2 class="text-center">CONTACT US</h2>
            </div>
            <form method="post" data-form-title="CONTACT US">
              <input type="hidden" data-form-email="true">
              <div class="form-group">
                <input type="text" class="form-control" name="name" required="" placeholder="Name*" data-form-field="Name">
              </div>
              <div class="form-group">
                <input type="email" class="form-control" name="email" required="" placeholder="Email*" data-form-field="Email">
              </div>
              <div class="form-group">
                <input type="tel" class="form-control" name="phone" placeholder="Phone" data-form-field="Phone">
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" placeholder="Message" rows="7" data-form-field="Message"></textarea>
              </div>
              <div>
                <button type="submit" class="btn btn-lg btn-danger">CONTACT US</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/simple_pages/index.html.erb
<section id="bikes" class="container">
	<div class="row">
		<% for i in 1..9 do %>
			<div class="col-md-4 col-sm-12 col-xm-12">
				<%= image_tag("bikes/#{i}.png", class: "img-responsive logo") %>
			</div>
		<% end %>
	</div>
</section>


  